version: "3"
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    ports:
      - "8080:80"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
volumes:
  mysql:
    driver: local